[package]
name = "memecoin_price_predictor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
no-entrypoint = []

[dependencies]
borsh = "1.5.1"
solana-program = "2.0.2"
